server:
  port: 8000

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        # 1. User & Auth Service Route
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/v1/auth/**, /api/v1/users/**

        # 2. Salon & Service Management Service Route
        - id: salon-service
          uri: lb://SALON-SERVICE
          predicates:
            - Path=/api/v1/salons/**

        # 3. Booking & Appointment Service Route
        - id: booking-service
          uri: lb://BOOKING-SERVICE
          predicates:
            - Path=/api/v1/bookings/**

      default-filters:
        - PreserveHostHeader
        - AuthenticationFilter

      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowed-methods: "*"
            allowed-headers: "*"