server:
  port: 8084

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      server:
        webflux:

          discovery:
            locator:
              enabled: true
              lower-case-service-id: true

          routes:

            # =========================
            # USER SERVICE
            # =========================
            - id: user-service
              uri: lb://USER-SERVICE
              predicates:
                - Path=/api/v1/auth/**,/api/v1/users/**

            # =========================
            # SALON SERVICE
            # =========================
            - id: salon-service
              uri: lb://SALON-SERVICE
              predicates:
                - Path=/api/v1/salons/**

            # =========================
            # APPOINTMENT SERVICE
            # =========================
            - id: appointment-service
              uri: lb://APPOINTMENT-SERVICE
              predicates:
                - Path=/api/v1/appointments/**

          default-filters:
            - PreserveHostHeader
            - AuthenticationFilter

          globalcors:
            cors-configurations:
              '[/**]':
                allowedOrigins: "*"
                allowedMethods: "*"
                allowedHeaders: "*"

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

  instance:
    prefer-ip-address: true