server:
  port: 8001
  forward-headers-strategy: framework

spring:
  application:
    name: user-service

  mvc:
    problemdetails:
      enabled: true

  datasource:
    url: jdbc:mysql://localhost:14500/db-salon-user?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
    username: root
    password: sachi17953
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true